# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cranetestdoc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CraneTestDocWnd(object):
    def setupUi(self, CraneTestDocWnd):
        CraneTestDocWnd.setObjectName("CraneTestDocWnd")
        CraneTestDocWnd.resize(1152, 880)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CraneTestDocWnd)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(CraneTestDocWnd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testcase_tree = QtWidgets.QTreeWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testcase_tree.sizePolicy().hasHeightForWidth())
        self.testcase_tree.setSizePolicy(sizePolicy)
        self.testcase_tree.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.testcase_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.testcase_tree.setColumnCount(3)
        self.testcase_tree.setObjectName("testcase_tree")
        self.verticalLayout.addWidget(self.testcase_tree)
        self.selectall_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.selectall_checkbox.setObjectName("selectall_checkbox")
        self.verticalLayout.addWidget(self.selectall_checkbox)
        self.test_tabwidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_tabwidget.sizePolicy().hasHeightForWidth())
        self.test_tabwidget.setSizePolicy(sizePolicy)
        self.test_tabwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.test_tabwidget.setObjectName("test_tabwidget")
        self.test_result_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_result_tab.sizePolicy().hasHeightForWidth())
        self.test_result_tab.setSizePolicy(sizePolicy)
        self.test_result_tab.setObjectName("test_result_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.test_result_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.testSpecGroup = QtWidgets.QGroupBox(self.test_result_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testSpecGroup.sizePolicy().hasHeightForWidth())
        self.testSpecGroup.setSizePolicy(sizePolicy)
        self.testSpecGroup.setFlat(False)
        self.testSpecGroup.setObjectName("testSpecGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.testSpecGroup)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 13, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.test_caseidentify_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.test_caseidentify_edit.setObjectName("test_caseidentify_edit")
        self.gridLayout.addWidget(self.test_caseidentify_edit, 0, 1, 1, 1)
        self.test_env_combox = QtWidgets.QComboBox(self.testSpecGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_env_combox.sizePolicy().hasHeightForWidth())
        self.test_env_combox.setSizePolicy(sizePolicy)
        self.test_env_combox.setObjectName("test_env_combox")
        self.gridLayout.addWidget(self.test_env_combox, 13, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.test_item_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.test_item_edit.setObjectName("test_item_edit")
        self.gridLayout.addWidget(self.test_item_edit, 0, 4, 1, 2)
        self.precondation_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.precondation_edit.setObjectName("precondation_edit")
        self.gridLayout.addWidget(self.precondation_edit, 3, 1, 1, 10)
        self.require_trace_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.require_trace_edit.setObjectName("require_trace_edit")
        self.gridLayout.addWidget(self.require_trace_edit, 0, 10, 1, 1)
        self.qualified_method_combox = QtWidgets.QComboBox(self.testSpecGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualified_method_combox.sizePolicy().hasHeightForWidth())
        self.qualified_method_combox.setSizePolicy(sizePolicy)
        self.qualified_method_combox.setObjectName("qualified_method_combox")
        self.gridLayout.addWidget(self.qualified_method_combox, 13, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.testSpecGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.test_input_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.test_input_edit.setObjectName("test_input_edit")
        self.gridLayout.addWidget(self.test_input_edit, 4, 1, 1, 10)
        self.test_procedure_tabel = QtWidgets.QTableWidget(self.testSpecGroup)
        self.test_procedure_tabel.setAlternatingRowColors(True)
        self.test_procedure_tabel.setObjectName("test_procedure_tabel")
        self.test_procedure_tabel.setColumnCount(7)
        self.test_procedure_tabel.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.test_procedure_tabel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 6, item)
        self.test_procedure_tabel.horizontalHeader().setCascadingSectionResizes(False)
        self.test_procedure_tabel.horizontalHeader().setSortIndicatorShown(False)
        self.test_procedure_tabel.horizontalHeader().setStretchLastSection(False)
        self.test_procedure_tabel.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.test_procedure_tabel, 6, 1, 4, 10)
        self.test_content_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.test_content_edit.setObjectName("test_content_edit")
        self.gridLayout.addWidget(self.test_content_edit, 1, 1, 1, 10)
        self.estimate_rule_eidt = QtWidgets.QLineEdit(self.testSpecGroup)
        self.estimate_rule_eidt.setObjectName("estimate_rule_eidt")
        self.gridLayout.addWidget(self.estimate_rule_eidt, 10, 1, 1, 10)
        self.label_2 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.test_cat_combox = QtWidgets.QComboBox(self.testSpecGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_cat_combox.sizePolicy().hasHeightForWidth())
        self.test_cat_combox.setSizePolicy(sizePolicy)
        self.test_cat_combox.setEditable(True)
        self.test_cat_combox.setDuplicatesEnabled(True)
        self.test_cat_combox.setObjectName("test_cat_combox")
        self.gridLayout.addWidget(self.test_cat_combox, 0, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.testSpecGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 13, 0, 1, 1)
        self.remove_procdure_button = QtWidgets.QPushButton(self.testSpecGroup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_minus-circle_2561243.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_procdure_button.setIcon(icon)
        self.remove_procdure_button.setObjectName("remove_procdure_button")
        self.gridLayout.addWidget(self.remove_procdure_button, 8, 0, 1, 1)
        self.add_procedure_button = QtWidgets.QPushButton(self.testSpecGroup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_circle-add_226591.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_procedure_button.setIcon(icon1)
        self.add_procedure_button.setIconSize(QtCore.QSize(16, 16))
        self.add_procedure_button.setObjectName("add_procedure_button")
        self.gridLayout.addWidget(self.add_procedure_button, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.sys_prepare_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        self.sys_prepare_edit.setObjectName("sys_prepare_edit")
        self.gridLayout.addWidget(self.sys_prepare_edit, 2, 1, 1, 10)
        self.label_4 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.testSpecGroup)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 13, 6, 1, 1)
        self.safe_secret_edit = QtWidgets.QLineEdit(self.testSpecGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.safe_secret_edit.sizePolicy().hasHeightForWidth())
        self.safe_secret_edit.setSizePolicy(sizePolicy)
        self.safe_secret_edit.setObjectName("safe_secret_edit")
        self.gridLayout.addWidget(self.safe_secret_edit, 13, 8, 1, 3)
        self.verticalLayout_3.addWidget(self.testSpecGroup)
        self.testReportGroup = QtWidgets.QGroupBox(self.test_result_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testReportGroup.sizePolicy().hasHeightForWidth())
        self.testReportGroup.setSizePolicy(sizePolicy)
        self.testReportGroup.setObjectName("testReportGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.testReportGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.testReportGroup)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 6, 1, 2)
        self.correct_sheet_edit = QtWidgets.QLineEdit(self.testReportGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correct_sheet_edit.sizePolicy().hasHeightForWidth())
        self.correct_sheet_edit.setSizePolicy(sizePolicy)
        self.correct_sheet_edit.setObjectName("correct_sheet_edit")
        self.gridLayout_2.addWidget(self.correct_sheet_edit, 2, 7, 1, 2)
        self.test_person_join_edit = QtWidgets.QLineEdit(self.testReportGroup)
        self.test_person_join_edit.setObjectName("test_person_join_edit")
        self.gridLayout_2.addWidget(self.test_person_join_edit, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.testReportGroup)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.testReportGroup)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.testReportGroup)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.testReportGroup)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 6, 1, 1)
        self.test_data_edit = QtWidgets.QLineEdit(self.testReportGroup)
        self.test_data_edit.setObjectName("test_data_edit")
        self.gridLayout_2.addWidget(self.test_data_edit, 2, 1, 1, 1)
        self.test_date_timepickedit = QtWidgets.QDateTimeEdit(self.testReportGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_date_timepickedit.sizePolicy().hasHeightForWidth())
        self.test_date_timepickedit.setSizePolicy(sizePolicy)
        self.test_date_timepickedit.setCalendarPopup(True)
        self.test_date_timepickedit.setObjectName("test_date_timepickedit")
        self.gridLayout_2.addWidget(self.test_date_timepickedit, 0, 8, 1, 1)
        self.test_person_combox = QtWidgets.QComboBox(self.testReportGroup)
        self.test_person_combox.setEditable(True)
        self.test_person_combox.setObjectName("test_person_combox")
        self.gridLayout_2.addWidget(self.test_person_combox, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.testReportGroup)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.problem_sheet_edit = QtWidgets.QLineEdit(self.testReportGroup)
        self.problem_sheet_edit.setObjectName("problem_sheet_edit")
        self.gridLayout_2.addWidget(self.problem_sheet_edit, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.testReportGroup)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.test_diff_edit = QtWidgets.QLineEdit(self.testReportGroup)
        self.test_diff_edit.setObjectName("test_diff_edit")
        self.gridLayout_2.addWidget(self.test_diff_edit, 3, 1, 1, 4)
        self.verticalLayout_3.addWidget(self.testReportGroup)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.test_tabwidget.addTab(self.test_result_tab, "")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.process_progressbar = QtWidgets.QProgressBar(CraneTestDocWnd)
        self.process_progressbar.setProperty("value", 24)
        self.process_progressbar.setObjectName("process_progressbar")
        self.horizontalLayout.addWidget(self.process_progressbar)
        self.add_test_case_button = QtWidgets.QPushButton(CraneTestDocWnd)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_network_sans_add_103649.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_test_case_button.setIcon(icon2)
        self.add_test_case_button.setIconSize(QtCore.QSize(16, 16))
        self.add_test_case_button.setObjectName("add_test_case_button")
        self.horizontalLayout.addWidget(self.add_test_case_button)
        self.remove_test_case_button = QtWidgets.QPushButton(CraneTestDocWnd)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_UI_Basic_GLYPH-73_4733351.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_test_case_button.setIcon(icon3)
        self.remove_test_case_button.setObjectName("remove_test_case_button")
        self.horizontalLayout.addWidget(self.remove_test_case_button)
        self.save_test_case_button = QtWidgets.QPushButton(CraneTestDocWnd)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_export-share-upload_2931143.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_test_case_button.setIcon(icon4)
        self.save_test_case_button.setObjectName("save_test_case_button")
        self.horizontalLayout.addWidget(self.save_test_case_button)
        self.import_case_button = QtWidgets.QPushButton(CraneTestDocWnd)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_import-download-save_2931171.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_case_button.setIcon(icon5)
        self.import_case_button.setObjectName("import_case_button")
        self.horizontalLayout.addWidget(self.import_case_button)
        self.generate_doc_button = QtWidgets.QPushButton(CraneTestDocWnd)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/image/iconfinder_15_2134065.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_doc_button.setIcon(icon6)
        self.generate_doc_button.setObjectName("generate_doc_button")
        self.horizontalLayout.addWidget(self.generate_doc_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(CraneTestDocWnd)
        self.test_tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CraneTestDocWnd)
        CraneTestDocWnd.setTabOrder(self.test_tabwidget, self.test_caseidentify_edit)
        CraneTestDocWnd.setTabOrder(self.test_caseidentify_edit, self.test_cat_combox)
        CraneTestDocWnd.setTabOrder(self.test_cat_combox, self.require_trace_edit)
        CraneTestDocWnd.setTabOrder(self.require_trace_edit, self.test_content_edit)
        CraneTestDocWnd.setTabOrder(self.test_content_edit, self.sys_prepare_edit)
        CraneTestDocWnd.setTabOrder(self.sys_prepare_edit, self.precondation_edit)
        CraneTestDocWnd.setTabOrder(self.precondation_edit, self.test_input_edit)
        CraneTestDocWnd.setTabOrder(self.test_input_edit, self.test_procedure_tabel)
        CraneTestDocWnd.setTabOrder(self.test_procedure_tabel, self.estimate_rule_eidt)
        CraneTestDocWnd.setTabOrder(self.estimate_rule_eidt, self.test_date_timepickedit)
        CraneTestDocWnd.setTabOrder(self.test_date_timepickedit, self.test_data_edit)
        CraneTestDocWnd.setTabOrder(self.test_data_edit, self.correct_sheet_edit)

    def retranslateUi(self, CraneTestDocWnd):
        _translate = QtCore.QCoreApplication.translate
        CraneTestDocWnd.setWindowTitle(_translate("CraneTestDocWnd", "配置项测试工具"))
        self.groupBox.setTitle(_translate("CraneTestDocWnd", "用例列表"))
        self.testcase_tree.headerItem().setText(0, _translate("CraneTestDocWnd", "用例标识"))
        self.testcase_tree.headerItem().setText(1, _translate("CraneTestDocWnd", "用例名称"))
        self.testcase_tree.headerItem().setText(2, _translate("CraneTestDocWnd", "id"))
        self.selectall_checkbox.setText(_translate("CraneTestDocWnd", "全选"))
        self.testSpecGroup.setTitle(_translate("CraneTestDocWnd", "用例信息"))
        self.label_23.setText(_translate("CraneTestDocWnd", "合格性方法"))
        self.label_5.setText(_translate("CraneTestDocWnd", "系统准备"))
        self.label_9.setText(_translate("CraneTestDocWnd", "评估准则"))
        self.precondation_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.require_trace_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.label_8.setText(_translate("CraneTestDocWnd", "<html><head/><body><p>测试方法</p><p>测试结果</p></body></html>"))
        self.test_input_edit.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.verticalHeaderItem(0)
        item.setText(_translate("CraneTestDocWnd", "New Row"))
        item = self.test_procedure_tabel.verticalHeaderItem(1)
        item.setText(_translate("CraneTestDocWnd", "New Row"))
        item = self.test_procedure_tabel.verticalHeaderItem(2)
        item.setText(_translate("CraneTestDocWnd", "New Row"))
        item = self.test_procedure_tabel.horizontalHeaderItem(0)
        item.setText(_translate("CraneTestDocWnd", "序号"))
        item = self.test_procedure_tabel.horizontalHeaderItem(1)
        item.setText(_translate("CraneTestDocWnd", "测试步骤"))
        item = self.test_procedure_tabel.horizontalHeaderItem(2)
        item.setText(_translate("CraneTestDocWnd", "预期结果"))
        item = self.test_procedure_tabel.horizontalHeaderItem(3)
        item.setText(_translate("CraneTestDocWnd", "测试结果"))
        item = self.test_procedure_tabel.horizontalHeaderItem(4)
        item.setText(_translate("CraneTestDocWnd", "数据分析"))
        item = self.test_procedure_tabel.horizontalHeaderItem(5)
        item.setText(_translate("CraneTestDocWnd", "问题描述"))
        item = self.test_procedure_tabel.horizontalHeaderItem(6)
        item.setText(_translate("CraneTestDocWnd", "备注"))
        __sortingEnabled = self.test_procedure_tabel.isSortingEnabled()
        self.test_procedure_tabel.setSortingEnabled(False)
        item = self.test_procedure_tabel.item(0, 0)
        item.setText(_translate("CraneTestDocWnd", "1"))
        item = self.test_procedure_tabel.item(0, 1)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(0, 2)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(0, 3)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(0, 4)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(0, 5)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(0, 6)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 0)
        item.setText(_translate("CraneTestDocWnd", "2"))
        item = self.test_procedure_tabel.item(1, 1)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 2)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 3)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 4)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 5)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(1, 6)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 0)
        item.setText(_translate("CraneTestDocWnd", "3"))
        item = self.test_procedure_tabel.item(2, 1)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 2)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 3)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 4)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 5)
        item.setText(_translate("CraneTestDocWnd", "无"))
        item = self.test_procedure_tabel.item(2, 6)
        item.setText(_translate("CraneTestDocWnd", "无"))
        self.test_procedure_tabel.setSortingEnabled(__sortingEnabled)
        self.estimate_rule_eidt.setText(_translate("CraneTestDocWnd", "测试结果与预期结果一致"))
        self.label_2.setText(_translate("CraneTestDocWnd", "测试类别"))
        self.label.setText(_translate("CraneTestDocWnd", "用例标识"))
        self.label_3.setText(_translate("CraneTestDocWnd", "需求追溯"))
        self.label_6.setText(_translate("CraneTestDocWnd", "前提约束"))
        self.label_12.setText(_translate("CraneTestDocWnd", "用例名称"))
        self.label_10.setText(_translate("CraneTestDocWnd", "测试环境"))
        self.remove_procdure_button.setText(_translate("CraneTestDocWnd", "删除步骤"))
        self.add_procedure_button.setText(_translate("CraneTestDocWnd", "添加步骤"))
        self.label_7.setText(_translate("CraneTestDocWnd", "测试输入"))
        self.sys_prepare_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.label_4.setText(_translate("CraneTestDocWnd", "测试内容"))
        self.label_24.setText(_translate("CraneTestDocWnd", "安全保密"))
        self.safe_secret_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.testReportGroup.setTitle(_translate("CraneTestDocWnd", "测试结果附加信息"))
        self.label_13.setText(_translate("CraneTestDocWnd", "测试时间"))
        self.correct_sheet_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.test_person_join_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.label_15.setText(_translate("CraneTestDocWnd", "参加人员"))
        self.label_17.setText(_translate("CraneTestDocWnd", "问题单号"))
        self.label_16.setText(_translate("CraneTestDocWnd", "测试数据"))
        self.label_18.setText(_translate("CraneTestDocWnd", "更改单号"))
        self.test_data_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.test_date_timepickedit.setDisplayFormat(_translate("CraneTestDocWnd", "yyyy-MM-dd"))
        self.label_14.setText(_translate("CraneTestDocWnd", "测试人员"))
        self.problem_sheet_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.label_11.setText(_translate("CraneTestDocWnd", "测试差异"))
        self.test_diff_edit.setText(_translate("CraneTestDocWnd", "无"))
        self.test_tabwidget.setTabText(self.test_tabwidget.indexOf(self.test_result_tab), _translate("CraneTestDocWnd", "用例+测试结果"))
        self.add_test_case_button.setText(_translate("CraneTestDocWnd", "添加/更新用例"))
        self.remove_test_case_button.setText(_translate("CraneTestDocWnd", "删除所选用例"))
        self.save_test_case_button.setText(_translate("CraneTestDocWnd", "导出所选用例"))
        self.import_case_button.setText(_translate("CraneTestDocWnd", "导入用例"))
        self.generate_doc_button.setText(_translate("CraneTestDocWnd", "生成文档"))
import cranetestdoc_rc
