# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cranetestdoc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CraneTestDocWnd(object):
    def setupUi(self, CraneTestDocWnd):
        CraneTestDocWnd.setObjectName(_fromUtf8("CraneTestDocWnd"))
        CraneTestDocWnd.resize(1152, 880)
        self.verticalLayout_2 = QtGui.QVBoxLayout(CraneTestDocWnd)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(CraneTestDocWnd)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.testcase_tree = QtGui.QTreeWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testcase_tree.sizePolicy().hasHeightForWidth())
        self.testcase_tree.setSizePolicy(sizePolicy)
        self.testcase_tree.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.testcase_tree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.testcase_tree.setColumnCount(3)
        self.testcase_tree.setObjectName(_fromUtf8("testcase_tree"))
        self.verticalLayout.addWidget(self.testcase_tree)
        self.selectall_checkbox = QtGui.QCheckBox(self.groupBox)
        self.selectall_checkbox.setObjectName(_fromUtf8("selectall_checkbox"))
        self.verticalLayout.addWidget(self.selectall_checkbox)
        self.test_tabwidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_tabwidget.sizePolicy().hasHeightForWidth())
        self.test_tabwidget.setSizePolicy(sizePolicy)
        self.test_tabwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.test_tabwidget.setObjectName(_fromUtf8("test_tabwidget"))
        self.test_result_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_result_tab.sizePolicy().hasHeightForWidth())
        self.test_result_tab.setSizePolicy(sizePolicy)
        self.test_result_tab.setObjectName(_fromUtf8("test_result_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.test_result_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.testSpecGroup = QtGui.QGroupBox(self.test_result_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testSpecGroup.sizePolicy().hasHeightForWidth())
        self.testSpecGroup.setSizePolicy(sizePolicy)
        self.testSpecGroup.setFlat(False)
        self.testSpecGroup.setObjectName(_fromUtf8("testSpecGroup"))
        self.gridLayout = QtGui.QGridLayout(self.testSpecGroup)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_23 = QtGui.QLabel(self.testSpecGroup)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 13, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.testSpecGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.test_caseidentify_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.test_caseidentify_edit.setObjectName(_fromUtf8("test_caseidentify_edit"))
        self.gridLayout.addWidget(self.test_caseidentify_edit, 0, 1, 1, 1)
        self.test_env_combox = QtGui.QComboBox(self.testSpecGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_env_combox.sizePolicy().hasHeightForWidth())
        self.test_env_combox.setSizePolicy(sizePolicy)
        self.test_env_combox.setObjectName(_fromUtf8("test_env_combox"))
        self.gridLayout.addWidget(self.test_env_combox, 13, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.testSpecGroup)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.test_item_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.test_item_edit.setObjectName(_fromUtf8("test_item_edit"))
        self.gridLayout.addWidget(self.test_item_edit, 0, 4, 1, 2)
        self.precondation_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.precondation_edit.setObjectName(_fromUtf8("precondation_edit"))
        self.gridLayout.addWidget(self.precondation_edit, 3, 1, 1, 10)
        self.require_trace_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.require_trace_edit.setObjectName(_fromUtf8("require_trace_edit"))
        self.gridLayout.addWidget(self.require_trace_edit, 0, 10, 1, 1)
        self.qualified_method_combox = QtGui.QComboBox(self.testSpecGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualified_method_combox.sizePolicy().hasHeightForWidth())
        self.qualified_method_combox.setSizePolicy(sizePolicy)
        self.qualified_method_combox.setObjectName(_fromUtf8("qualified_method_combox"))
        self.gridLayout.addWidget(self.qualified_method_combox, 13, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.testSpecGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.test_input_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.test_input_edit.setObjectName(_fromUtf8("test_input_edit"))
        self.gridLayout.addWidget(self.test_input_edit, 4, 1, 1, 10)
        self.test_procedure_tabel = QtGui.QTableWidget(self.testSpecGroup)
        self.test_procedure_tabel.setAlternatingRowColors(True)
        self.test_procedure_tabel.setObjectName(_fromUtf8("test_procedure_tabel"))
        self.test_procedure_tabel.setColumnCount(7)
        self.test_procedure_tabel.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.test_procedure_tabel.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.test_procedure_tabel.setItem(2, 6, item)
        self.test_procedure_tabel.horizontalHeader().setCascadingSectionResizes(False)
        self.test_procedure_tabel.horizontalHeader().setSortIndicatorShown(False)
        self.test_procedure_tabel.horizontalHeader().setStretchLastSection(False)
        self.test_procedure_tabel.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.test_procedure_tabel, 6, 1, 4, 10)
        self.test_content_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.test_content_edit.setObjectName(_fromUtf8("test_content_edit"))
        self.gridLayout.addWidget(self.test_content_edit, 1, 1, 1, 10)
        self.estimate_rule_eidt = QtGui.QLineEdit(self.testSpecGroup)
        self.estimate_rule_eidt.setObjectName(_fromUtf8("estimate_rule_eidt"))
        self.gridLayout.addWidget(self.estimate_rule_eidt, 10, 1, 1, 10)
        self.label_2 = QtGui.QLabel(self.testSpecGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.test_cat_combox = QtGui.QComboBox(self.testSpecGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_cat_combox.sizePolicy().hasHeightForWidth())
        self.test_cat_combox.setSizePolicy(sizePolicy)
        self.test_cat_combox.setEditable(True)
        self.test_cat_combox.setDuplicatesEnabled(True)
        self.test_cat_combox.setObjectName(_fromUtf8("test_cat_combox"))
        self.gridLayout.addWidget(self.test_cat_combox, 0, 8, 1, 1)
        self.label = QtGui.QLabel(self.testSpecGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.testSpecGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 9, 1, 1)
        self.label_6 = QtGui.QLabel(self.testSpecGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.testSpecGroup)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.testSpecGroup)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 13, 0, 1, 1)
        self.remove_procdure_button = QtGui.QPushButton(self.testSpecGroup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_minus-circle_2561243.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_procdure_button.setIcon(icon)
        self.remove_procdure_button.setObjectName(_fromUtf8("remove_procdure_button"))
        self.gridLayout.addWidget(self.remove_procdure_button, 8, 0, 1, 1)
        self.add_procedure_button = QtGui.QPushButton(self.testSpecGroup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_circle-add_226591.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_procedure_button.setIcon(icon1)
        self.add_procedure_button.setIconSize(QtCore.QSize(16, 16))
        self.add_procedure_button.setObjectName(_fromUtf8("add_procedure_button"))
        self.gridLayout.addWidget(self.add_procedure_button, 7, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.testSpecGroup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.sys_prepare_edit = QtGui.QLineEdit(self.testSpecGroup)
        self.sys_prepare_edit.setObjectName(_fromUtf8("sys_prepare_edit"))
        self.gridLayout.addWidget(self.sys_prepare_edit, 2, 1, 1, 10)
        self.label_4 = QtGui.QLabel(self.testSpecGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.testSpecGroup)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 13, 6, 1, 1)
        self.safe_secret_edit = QtGui.QLineEdit(self.testSpecGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.safe_secret_edit.sizePolicy().hasHeightForWidth())
        self.safe_secret_edit.setSizePolicy(sizePolicy)
        self.safe_secret_edit.setObjectName(_fromUtf8("safe_secret_edit"))
        self.gridLayout.addWidget(self.safe_secret_edit, 13, 8, 1, 3)
        self.verticalLayout_3.addWidget(self.testSpecGroup)
        self.testReportGroup = QtGui.QGroupBox(self.test_result_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testReportGroup.sizePolicy().hasHeightForWidth())
        self.testReportGroup.setSizePolicy(sizePolicy)
        self.testReportGroup.setObjectName(_fromUtf8("testReportGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.testReportGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_13 = QtGui.QLabel(self.testReportGroup)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 6, 1, 2)
        self.correct_sheet_edit = QtGui.QLineEdit(self.testReportGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correct_sheet_edit.sizePolicy().hasHeightForWidth())
        self.correct_sheet_edit.setSizePolicy(sizePolicy)
        self.correct_sheet_edit.setObjectName(_fromUtf8("correct_sheet_edit"))
        self.gridLayout_2.addWidget(self.correct_sheet_edit, 2, 7, 1, 2)
        self.test_person_join_edit = QtGui.QLineEdit(self.testReportGroup)
        self.test_person_join_edit.setObjectName(_fromUtf8("test_person_join_edit"))
        self.gridLayout_2.addWidget(self.test_person_join_edit, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.testReportGroup)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.testReportGroup)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.testReportGroup)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.testReportGroup)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 6, 1, 1)
        self.test_data_edit = QtGui.QLineEdit(self.testReportGroup)
        self.test_data_edit.setObjectName(_fromUtf8("test_data_edit"))
        self.gridLayout_2.addWidget(self.test_data_edit, 2, 1, 1, 1)
        self.test_date_timepickedit = QtGui.QDateTimeEdit(self.testReportGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_date_timepickedit.sizePolicy().hasHeightForWidth())
        self.test_date_timepickedit.setSizePolicy(sizePolicy)
        self.test_date_timepickedit.setCalendarPopup(True)
        self.test_date_timepickedit.setObjectName(_fromUtf8("test_date_timepickedit"))
        self.gridLayout_2.addWidget(self.test_date_timepickedit, 0, 8, 1, 1)
        self.test_person_combox = QtGui.QComboBox(self.testReportGroup)
        self.test_person_combox.setEditable(True)
        self.test_person_combox.setObjectName(_fromUtf8("test_person_combox"))
        self.gridLayout_2.addWidget(self.test_person_combox, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.testReportGroup)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.problem_sheet_edit = QtGui.QLineEdit(self.testReportGroup)
        self.problem_sheet_edit.setObjectName(_fromUtf8("problem_sheet_edit"))
        self.gridLayout_2.addWidget(self.problem_sheet_edit, 2, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.testReportGroup)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.test_diff_edit = QtGui.QLineEdit(self.testReportGroup)
        self.test_diff_edit.setObjectName(_fromUtf8("test_diff_edit"))
        self.gridLayout_2.addWidget(self.test_diff_edit, 3, 1, 1, 4)
        self.verticalLayout_3.addWidget(self.testReportGroup)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.test_tabwidget.addTab(self.test_result_tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.process_progressbar = QtGui.QProgressBar(CraneTestDocWnd)
        self.process_progressbar.setProperty("value", 24)
        self.process_progressbar.setObjectName(_fromUtf8("process_progressbar"))
        self.horizontalLayout.addWidget(self.process_progressbar)
        self.add_test_case_button = QtGui.QPushButton(CraneTestDocWnd)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_network_sans_add_103649.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_test_case_button.setIcon(icon2)
        self.add_test_case_button.setIconSize(QtCore.QSize(16, 16))
        self.add_test_case_button.setDefault(True)
        self.add_test_case_button.setObjectName(_fromUtf8("add_test_case_button"))
        self.horizontalLayout.addWidget(self.add_test_case_button)
        self.remove_test_case_button = QtGui.QPushButton(CraneTestDocWnd)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_UI_Basic_GLYPH-73_4733351.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_test_case_button.setIcon(icon3)
        self.remove_test_case_button.setObjectName(_fromUtf8("remove_test_case_button"))
        self.horizontalLayout.addWidget(self.remove_test_case_button)
        self.save_test_case_button = QtGui.QPushButton(CraneTestDocWnd)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_export-share-upload_2931143.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_test_case_button.setIcon(icon4)
        self.save_test_case_button.setObjectName(_fromUtf8("save_test_case_button"))
        self.horizontalLayout.addWidget(self.save_test_case_button)
        self.import_case_button = QtGui.QPushButton(CraneTestDocWnd)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_import-download-save_2931171.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_case_button.setIcon(icon5)
        self.import_case_button.setObjectName(_fromUtf8("import_case_button"))
        self.horizontalLayout.addWidget(self.import_case_button)
        self.generate_doc_button = QtGui.QPushButton(CraneTestDocWnd)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/iconfinder_15_2134065.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_doc_button.setIcon(icon6)
        self.generate_doc_button.setObjectName(_fromUtf8("generate_doc_button"))
        self.horizontalLayout.addWidget(self.generate_doc_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(CraneTestDocWnd)
        self.test_tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CraneTestDocWnd)
        CraneTestDocWnd.setTabOrder(self.testcase_tree, self.test_tabwidget)
        CraneTestDocWnd.setTabOrder(self.test_tabwidget, self.test_caseidentify_edit)
        CraneTestDocWnd.setTabOrder(self.test_caseidentify_edit, self.test_item_edit)
        CraneTestDocWnd.setTabOrder(self.test_item_edit, self.test_cat_combox)
        CraneTestDocWnd.setTabOrder(self.test_cat_combox, self.require_trace_edit)
        CraneTestDocWnd.setTabOrder(self.require_trace_edit, self.test_content_edit)
        CraneTestDocWnd.setTabOrder(self.test_content_edit, self.sys_prepare_edit)
        CraneTestDocWnd.setTabOrder(self.sys_prepare_edit, self.precondation_edit)
        CraneTestDocWnd.setTabOrder(self.precondation_edit, self.test_input_edit)
        CraneTestDocWnd.setTabOrder(self.test_input_edit, self.test_procedure_tabel)
        CraneTestDocWnd.setTabOrder(self.test_procedure_tabel, self.add_procedure_button)
        CraneTestDocWnd.setTabOrder(self.add_procedure_button, self.remove_procdure_button)
        CraneTestDocWnd.setTabOrder(self.remove_procdure_button, self.estimate_rule_eidt)
        CraneTestDocWnd.setTabOrder(self.estimate_rule_eidt, self.test_env_combox)
        CraneTestDocWnd.setTabOrder(self.test_env_combox, self.qualified_method_combox)
        CraneTestDocWnd.setTabOrder(self.qualified_method_combox, self.safe_secret_edit)
        CraneTestDocWnd.setTabOrder(self.safe_secret_edit, self.test_person_combox)
        CraneTestDocWnd.setTabOrder(self.test_person_combox, self.test_person_join_edit)
        CraneTestDocWnd.setTabOrder(self.test_person_join_edit, self.test_date_timepickedit)
        CraneTestDocWnd.setTabOrder(self.test_date_timepickedit, self.test_data_edit)
        CraneTestDocWnd.setTabOrder(self.test_data_edit, self.problem_sheet_edit)
        CraneTestDocWnd.setTabOrder(self.problem_sheet_edit, self.correct_sheet_edit)
        CraneTestDocWnd.setTabOrder(self.correct_sheet_edit, self.test_diff_edit)
        CraneTestDocWnd.setTabOrder(self.test_diff_edit, self.add_test_case_button)
        CraneTestDocWnd.setTabOrder(self.add_test_case_button, self.remove_test_case_button)
        CraneTestDocWnd.setTabOrder(self.remove_test_case_button, self.save_test_case_button)
        CraneTestDocWnd.setTabOrder(self.save_test_case_button, self.import_case_button)
        CraneTestDocWnd.setTabOrder(self.import_case_button, self.generate_doc_button)
        CraneTestDocWnd.setTabOrder(self.generate_doc_button, self.selectall_checkbox)

    def retranslateUi(self, CraneTestDocWnd):
        CraneTestDocWnd.setWindowTitle(_translate("CraneTestDocWnd", "配置项测试工具", None))
        self.groupBox.setTitle(_translate("CraneTestDocWnd", "用例列表", None))
        self.testcase_tree.headerItem().setText(0, _translate("CraneTestDocWnd", "用例标识", None))
        self.testcase_tree.headerItem().setText(1, _translate("CraneTestDocWnd", "用例名称", None))
        self.testcase_tree.headerItem().setText(2, _translate("CraneTestDocWnd", "id", None))
        self.selectall_checkbox.setText(_translate("CraneTestDocWnd", "全选", None))
        self.testSpecGroup.setTitle(_translate("CraneTestDocWnd", "用例信息", None))
        self.label_23.setText(_translate("CraneTestDocWnd", "合格性方法", None))
        self.label_5.setText(_translate("CraneTestDocWnd", "系统准备", None))
        self.label_9.setText(_translate("CraneTestDocWnd", "评估准则", None))
        self.precondation_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.require_trace_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.label_8.setText(_translate("CraneTestDocWnd", "<html><head/><body><p>测试方法</p><p>测试结果</p></body></html>", None))
        self.test_input_edit.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.verticalHeaderItem(0)
        item.setText(_translate("CraneTestDocWnd", "New Row", None))
        item = self.test_procedure_tabel.verticalHeaderItem(1)
        item.setText(_translate("CraneTestDocWnd", "New Row", None))
        item = self.test_procedure_tabel.verticalHeaderItem(2)
        item.setText(_translate("CraneTestDocWnd", "New Row", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(0)
        item.setText(_translate("CraneTestDocWnd", "序号", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(1)
        item.setText(_translate("CraneTestDocWnd", "测试步骤", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(2)
        item.setText(_translate("CraneTestDocWnd", "预期结果", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(3)
        item.setText(_translate("CraneTestDocWnd", "测试结果", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(4)
        item.setText(_translate("CraneTestDocWnd", "数据分析", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(5)
        item.setText(_translate("CraneTestDocWnd", "问题描述", None))
        item = self.test_procedure_tabel.horizontalHeaderItem(6)
        item.setText(_translate("CraneTestDocWnd", "备注", None))
        __sortingEnabled = self.test_procedure_tabel.isSortingEnabled()
        self.test_procedure_tabel.setSortingEnabled(False)
        item = self.test_procedure_tabel.item(0, 0)
        item.setText(_translate("CraneTestDocWnd", "1", None))
        item = self.test_procedure_tabel.item(0, 1)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(0, 2)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(0, 3)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(0, 4)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(0, 5)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(0, 6)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 0)
        item.setText(_translate("CraneTestDocWnd", "2", None))
        item = self.test_procedure_tabel.item(1, 1)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 2)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 3)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 4)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 5)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(1, 6)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 0)
        item.setText(_translate("CraneTestDocWnd", "3", None))
        item = self.test_procedure_tabel.item(2, 1)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 2)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 3)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 4)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 5)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        item = self.test_procedure_tabel.item(2, 6)
        item.setText(_translate("CraneTestDocWnd", "无", None))
        self.test_procedure_tabel.setSortingEnabled(__sortingEnabled)
        self.estimate_rule_eidt.setText(_translate("CraneTestDocWnd", "测试结果与预期结果一致", None))
        self.label_2.setText(_translate("CraneTestDocWnd", "测试类别", None))
        self.label.setText(_translate("CraneTestDocWnd", "用例标识", None))
        self.label_3.setText(_translate("CraneTestDocWnd", "需求追溯", None))
        self.label_6.setText(_translate("CraneTestDocWnd", "前提约束", None))
        self.label_12.setText(_translate("CraneTestDocWnd", "用例名称", None))
        self.label_10.setText(_translate("CraneTestDocWnd", "测试环境", None))
        self.remove_procdure_button.setText(_translate("CraneTestDocWnd", "删除步骤", None))
        self.add_procedure_button.setText(_translate("CraneTestDocWnd", "添加步骤", None))
        self.label_7.setText(_translate("CraneTestDocWnd", "测试输入", None))
        self.sys_prepare_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.label_4.setText(_translate("CraneTestDocWnd", "测试内容", None))
        self.label_24.setText(_translate("CraneTestDocWnd", "安全保密", None))
        self.safe_secret_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.testReportGroup.setTitle(_translate("CraneTestDocWnd", "测试结果附加信息", None))
        self.label_13.setText(_translate("CraneTestDocWnd", "测试时间", None))
        self.correct_sheet_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.test_person_join_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.label_15.setText(_translate("CraneTestDocWnd", "参加人员", None))
        self.label_17.setText(_translate("CraneTestDocWnd", "问题单号", None))
        self.label_16.setText(_translate("CraneTestDocWnd", "测试数据", None))
        self.label_18.setText(_translate("CraneTestDocWnd", "更改单号", None))
        self.test_data_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.test_date_timepickedit.setDisplayFormat(_translate("CraneTestDocWnd", "yyyy-MM-dd", None))
        self.label_14.setText(_translate("CraneTestDocWnd", "测试人员", None))
        self.problem_sheet_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.label_11.setText(_translate("CraneTestDocWnd", "测试差异", None))
        self.test_diff_edit.setText(_translate("CraneTestDocWnd", "无", None))
        self.test_tabwidget.setTabText(self.test_tabwidget.indexOf(self.test_result_tab), _translate("CraneTestDocWnd", "用例+测试结果", None))
        self.add_test_case_button.setText(_translate("CraneTestDocWnd", "添加/更新用例(&A)", None))
        self.add_test_case_button.setShortcut(_translate("CraneTestDocWnd", "Alt+A", None))
        self.remove_test_case_button.setText(_translate("CraneTestDocWnd", "删除所选用例(&D)", None))
        self.remove_test_case_button.setShortcut(_translate("CraneTestDocWnd", "Alt+D", None))
        self.save_test_case_button.setText(_translate("CraneTestDocWnd", "导出所选用例(&E)", None))
        self.save_test_case_button.setShortcut(_translate("CraneTestDocWnd", "Alt+E", None))
        self.import_case_button.setText(_translate("CraneTestDocWnd", "导入用例(&I)", None))
        self.import_case_button.setShortcut(_translate("CraneTestDocWnd", "Alt+I", None))
        self.generate_doc_button.setText(_translate("CraneTestDocWnd", "生成文档(&G)", None))
        self.generate_doc_button.setShortcut(_translate("CraneTestDocWnd", "Alt+G", None))

import icon_rc
